name: build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install npm dependencies
      run: npm install

    - name: Run backend
      run: npm run start-be &
      env:
        CI: true

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Run frontend
      run: npm run start-fe &
#      env:
#        CI: true

    - name: Run UI tests
      run: npm run test:ui
#      env:
#        CI: true
